// Code generated by github.com/hasura/ndc-sdk-go/codegen, DO NOT EDIT.
package functions

import (
	"github.com/hasura/ndc-sdk-go/utils"
)

// FromValue decodes values from map
func (j *HelloArguments) FromValue(input map[string]any) error {
	var err error
	j.Count, err = utils.GetNullableInt[int](input, "count")
	if err != nil {
		return err
	}
	j.Greeting, err = utils.GetString(input, "greeting")
	if err != nil {
		return err
	}
	return nil
}

// ToMap encodes the struct to a value map
func (j CreateAuthorResult) ToMap() map[string]any {
	result := map[string]any{
		"id":   j.ID,
		"name": j.Name,
	}
	return result
}

// ToMap encodes the struct to a value map
func (j HelloResult) ToMap() map[string]any {
	result := map[string]any{
		"count": j.Count,
		"reply": j.Reply,
	}
	return result
}
